apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: projetok8s  
spec:
  type: ClusterIP 
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090