apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: projetok8s
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 10Gi