apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: projetok8s
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000         
      targetPort: 3000    
      nodePort: 31000 