apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: projetok8s  
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'calculadora'
        static_configs:
          - targets: ['host.docker.internal:15001']  
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']