apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: projetok8s
spec:
  type: ClusterIP
  selector:
    app: redis-deploy
  ports:
    - protocol : TCP
      port: 6379
      targetPort: 6379
      