apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetofinal-deploy
  namespace: projetok8s
  labels:
    app: projetofinal-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: projetofinal-deploy
  template:
    metadata:
      labels:
        app: projetofinal-deploy
    spec:
      containers:
      - name: calculadora
        image: edunlima/projetofinal:latest
        command: ["sh", "-c", "while do; java -jar app.jar; sleep 10;"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 15002
          initialDelaySeconds: 45
          periodSeconds: 10   
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 15002
          initialDelaySeconds: 20
          periodSeconds: 5
          
       
