apiVersion: v1
kind: Service
metadata:
  name: projetofinal-service
  namespace: projetok8s
spec:
  type: NodePort
  selector:
    app: projetofinal-deploy
  ports:
    - protocol : TCP
      port: 8080
      targetPort: 8080
      nodePort: 31556
